name: "Unit testing"
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "npm ci"
      run: npm ci

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test